core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")), Versão do Django
    path("contas/", include("contas.urls")),  # url do app de contas
    path("perfil/", include("perfil.urls")),  # url do app de perfil
    path("config/", include("config.urls")),  # url do app de config
    path("", include("pages.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contas/models.py
import re
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email), **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **kwargs):
        kwargs.setdefault('is_staff', True)
        kwargs.setdefault('is_superuser', True)
        return self.create_user(email, password, **kwargs)


class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True, null=True)
    email = models.EmailField(unique=True, max_length=255)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField('date joined', auto_now_add=True)
    force_change_password = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    def requires_password_change(self):
        return self.force_change_password

    def save(self, *args, **kwargs):
        get_email = self.email.split("@")[0]
        email = re.sub(r"[^a-zA-Z0-9]", "", get_email)
        self.username = email
        super(MyUser, self).save(*args, **kwargs)

apps/base/views.py
from django.shortcuts import render

# Create your views here.

apps/base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Descrição do conteúdo do site">
    <meta name="keywords" content="palavras-chave separadas por vírgula">
    <meta name="author" content="Nome do autor">

    <title>{% block title %}{% endblock %}</title>

    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    {% include "components/navbar.html" %}
    {% include "components/logout.html" %}
    {% include "components/message.html" %}
    
    {% block content %}{% endblock %}
    <!-- JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
        integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block scripts %}{% endblock scripts %}
</body>

</html>

apps/base/templates/base_auth.html
{% extends 'base.html' %}
{% block title %}Autenticação{% endblock %}
{% block content %}
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row g-lg-5 py-5">
        <div class="col-lg-7"></div>
        <div class="col-md-10 mx-auto col-lg-5 p-4 p-md-5 rounded-4 bg-light shadow-sm">
            {% block content_auth %}{% endblock %}
            <div class="text-muted py-4">
                <small>Copyright© 2023 Name</small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/base/templates/base_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Descrição do conteúdo do site">
    <meta name="keywords" content="palavras-chave separadas por vírgula">
    <meta name="author" content="Nome do autor">
    <title>{% block title %}{% endblock %}</title>

    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Font Awesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
        integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc"
        crossorigin="anonymous"></script>

</head>

<body>
    {% include "components/logout.html" %}
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top" style="height: 70px">
        <div class="container-fluid">
            <a class="navbar-brand mx-5" href="/">
                <img src="{% static 'images/d-logo.png' %}" width="130" alt="" loading="lazy" />
            </a>
            <a class="navbar-toggler border-0" data-bs-toggle="collapse" data-bs-target="#sidebarMenu"
                aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="link-light fas fa-align-left fa-2x me-3"></i>
            </a>
            <div class="navbar-nav ms-auto d-flex flex-row">
                <a class="link-light p-2" href="{% url 'perfil' user.username %}">
                    <i class="fas fa-user mx-2"></i>{{user.first_name}} {{user.last_name}}
                </a>


                <button class="btn btn-danger" data-bs-toggle="modal" href="#logoutModal">Logout</button>
            </div>
        </div>
    </nav>

    <!-- Sidebar -->
    <div id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-secondary">
        <div class="list-group gap-2">
            <button type="button" class="btn btn-warning active" aria-current="true"
                onclick="location.href='{% url 'home' %}'">
                <i class="fas fa-arrow-left me-2"></i>Site</button>


            <button type="button" class="btn btn-light" aria-current="true"
                onclick="location.href='{% url 'painel' %}'">
                <i class="fas fa-tachometer-alt me-2"></i>Painel</button>


            <button type="button" class="btn btn-light"><i class="fas fa-file-alt me-2"></i>Relatórios</button>


            {% if perms.contas.view_myuser %}
            <button type="button" class="btn btn-light" onclick="location.href='{% url 'lista_usuarios' %}'">
                <i class="fas fa-users me-2"></i>Usuários do Sistema</button>
            {% endif %}

            <button type="button" class="btn btn-light" onclick="location.href='{% url 'configuracao' %}'">
                <i class="fas fa-cog me-2"></i>Configurações</button>
        </div>
    </div>

    <!-- Container -->
    <div class="bloco">
        {% include 'components/message.html' %}
        {% block content_dash %}
        {% endblock %}
    </div>

    <footer class="nav-bottom py-2 bg-light mt-auto fixed-bottom">
        <div class="container-fluid px-4 mt-auto">
            <div class="d-flex align-items-center justify-content-between">
                <div class="text-muted">
                    <a>Core</a>
                </div>
                <div class="text-muted">
                    <a>Release 1.0.0 <br> Patch 01</a>
                </div>
                <a class="text-muted">2023 Copyright &copy; Nome</a>
                <div>
                    <a class="text-muted" href="#">Politica de Privacidade</a>
                    &middot;
                    <a class="text-muted" href="#">Termos &amp; de condições</a>
                </div>
            </div>
        </div>
    </footer>

    <!-- JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>